-   id: kustomize
    name: kustomize (via docker)
    description: kustomize provided by docker
    entry: kustomize build
    language: system
    args: []
    always_run: true
    pass_filenames: false
