- id: kustomize
  name: kustomize
  description: kustomize
  entry: kustomize build
  language: system
  args: []

- id: helm-lint
  name: helm-lint
  description: helm-lint
  entry: helm lint
  language: system
  args: []

- id: helm-template
  name: helm-template
  description: helm-template
  entry: helm template
  language: system
  args: []

- id: helm-install
  name: helm-install
  description: helm-install
  entry: helm install
  language: system
  args: ["--dry-run=client"]
